version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  labels:
  - "category: engineering"
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: axe-core
    versions:
    - ">= 0"
  - dependency-name: "@axe-core/puppeteer"
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
  - dependency-name: license-check-and-add
    versions:
    - 4.0.1
  - dependency-name: apify
    versions:
    - 1.0.1
  - dependency-name: apify-shared
    versions:
    - 0.6.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: nuget
  directory: "/packages/web-workers"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  labels:
  - "category: engineering"
  - dependencies
  ignore:
  - dependency-name: Microsoft.Azure.WebJobs.Extensions.DurableTask
    versions:
    - 2.4.2
  commit-message:
    prefix: chore
    include: scope
